### ISSUE TITLE
riscv-tests vs riscv-compliance

### ISSUE THREAD

**Issue by T3KT4K** [riscv/riscv-compliance#114]
What are the differences in the goals of the two projects? It seems there is some overlap so I am slightly confused.

**Comment by jeremybennett** [comment]
This is the repository of the RISC-V compliance task group. It aims to provide a set of tests which any implementation must pass to be certified as compliant with the RISC-V specification.  Note that this is not comprehensive verification of a design, just sufficient to give confidence that the implementation meets the specification.

riscv-tests is a repository of unit tests for RISC-V processors, largely maintained by the SiFive engineering team. It includes tests of things like semihosting, which are about the software architecture built on top of the RISC-V hardware.

HTH

**Comment by T3KT4K** [comment]
Understood. Thanks
