### ISSUE TITLE
Cannot build sail to be used as riscv-compliance target

### ISSUE THREAD

**Issue by Imperas** [riscv/riscv-compliance#117]
@pmundkur 
Hi Prashant, 
are you the owner for the sail integration into the compliance framework ?
could I ask you to take a look at this issue I have raised on sail https://github.com/rems-project/sail-riscv/issues/59
It appears to generate a syntax error, but this is building from the Master branch
Is the Master branch the correct version to use, or is there a release ?

Thx
Lee

**Comment by pmundkur** [comment]
You should be able to use the master branch of sail-riscv.  It looks like you are using an outdated sail compiler (version 0.10).  The current version in opam is 0.13.

**Comment by allenjbaum** [comment]
IF this answer is correct, could you please close the issue?

**Comment by eroom1966** [comment]
I managed to resolve this - thanks
