### ISSUE TITLE
compressed jump tests stores addresses in to signature

### ISSUE THREAD

**Issue by hajekra** [riscv/riscv-compliance#12]
Tests c-jalt and c-jr store value from link register directly into signature. Signature should not be dependant on program location in memory.

**Comment by eroom1966** [comment]
@hajekra 
I have committed a fix to these tests which do not store the absolute address of the link register 
this should not cause an issue when linking the code to a different target location

**Comment by hajekra** [comment]
@eroom1966 
Thank you. I can confirm it is working.

I would suggest divide
