### ISSUE TITLE
compressed tests are using non-compressed instructions

### ISSUE THREAD

**Issue by hajekra** [riscv/riscv-compliance#13]
Following macros in test_macros.h are used for testing compressed instructions but do not use it directly:
TEST_CLWSP, TEST_CSWSP, TEST_CADDI16SP, TEST_CADDI4SPN.

**Comment by eroom1966** [comment]
Hi hajekra

As I recall, I could not get the assembler we were using to accept some of the compressed instructions by name, for example c.addi16sp

I have found that constructing an assembler instruction correctly, it will map to the compressed instruction
are you saying that you have been able to assemble code using the mnemonic 
c.addi16sp ?

If so, can you tell me what version of the assembler you used ?
Thx

**Comment by hajekra** [comment]
Hi,

I am using riscv64-unknown-elf-gcc (GCC) 7.1.1 20170509. In asm file I used "c.addi16sp sp, 0x20".

Radek H.

**Comment by Imperas** [comment]
@hajekra 
Thanks for clarification
fixed in commit 57049ee

**Comment by hajekra** [comment]
@Imperas 
Thanks, closing this issue.
