### ISSUE TITLE
How to redirect address of begin_signature 

### ISSUE THREAD

**Issue by davidmlw** [riscv/riscv-compliance#130]
As discussed in other threads, not all test cases in riscv-compliance are self-checking, some cases dump the execution results and depend on environment to check the signature results.

Is there an elegant way to redirect or specific the address of `begin_signature` in `link.ld` script? In this way, one can provide a virtual device to handle the execution results, rather than hack the main memory address bus.

https://github.com/riscv/riscv-compliance/blob/7cc155620865297512cdace3c696441e3977462a/riscv-test-env/p/riscv_test.h#L237-L251

**Comment by stnolting** [comment]
I am using the `RV_COMPLIANCE_HALT` macro to copy the data from the signature region to a memory-mapped output device (at address 0xFFFFFF88). Maybe this can solve your problem.

```
#define RV_COMPLIANCE_HALT                                                    \
  	la a0, begin_signature;                                               \
	la a1, end_signature;                                                 \
        li a2, 0xFFFFFF88;                                                    \
        copy_loop:                                                            \
        beq a0, a1, copy_loop_end;                                            \
        lw t0, 0(a0);                                                         \
        sw t0, 0(a2);                                                         \
        addi a0, a0, 4;                                                       \
        j copy_loop;                                                          \
        copy_loop_end:                                                        \
        j copy_loop_end;                                                      \
        RVTEST_PASS                                                           \
```

**Comment by davidmlw** [comment]
Nice solution! I was stucked by link script.

> I am using the `RV_COMPLIANCE_HALT` macro to copy the data from the signature region to a memory-mapped output device (at address 0xFFFFFF88). Maybe this can solve your problem.
> 
> ```
> #define RV_COMPLIANCE_HALT                                                    \
>   	la a0, begin_signature;                                               \
> 	la a1, end_signature;                                                 \
>         li a2, 0xFFFFFF88;                                                    \
>         copy_loop:                                                            \
>         beq a0, a1, copy_loop_end;                                            \
>         lw t0, 0(a0);                                                         \
>         sw t0, 0(a2);                                                         \
>         addi a0, a0, 4;                                                       \
>         j copy_loop;                                                          \
>         copy_loop_end:                                                        \
>         j copy_loop_end;                                                      \
>         RVTEST_PASS                                                           \
> ```

**Comment by allenjbaum** [comment]
IF you have the answer you need, could you please close this issue?
