### ISSUE TITLE
what is the state of core GPRs after reset? 

### ISSUE THREAD

**Issue by agrobman** [riscv/riscv-compliance#24]
Are GPRs ( x1- x31) reset by the CPU reset?

**Comment by aswaterman** [comment]
https://github.com/riscv/riscv-isa-manual/blob/master/src/machine.tex#L2274

Short answer is no.

**Comment by agrobman** [comment]
If we reset GPRs does this make our design non-compliant with RISC-V architecture?

**Comment by aswaterman** [comment]
No, that's fine, "everything is reset" is one valid implementation of "other hart state is unspecified"
