### ISSUE TITLE
The golden results of rv32ui and rv64ui should be different

### ISSUE THREAD

**Issue by RolfyYu** [riscv/riscv-compliance#30]
Since there is a "CHECK_XLEN" macro, 
the first word(double word) of begin_signature will set to 1 if XLEN is 64.
If XLEN is 32, the first and second word of begin_signature are 0xffff_ffff.

**Comment by eroom1966** [comment]
At the moment these were setup as placeholders, the rv64* all need setting up correctly, and enhancing the coverage.

**Comment by allenjbaum** [comment]
Is this a nice-to-have, or does cause tests to fail?
I know some tests that use constants fail in RV64 because constants are not sign extended in RV64, but that is slightly different than what I think this is about.

**Comment by neelgala** [comment]
the rv64* tests would require a focused effort. As Lee mentioned, they have to re-written with coverage-driven-strategy rather than re-use-rv32 strategy. Since this is a good enough effort I would suggest diong this in the next version.

**Comment by allenjbaum** [comment]
I tend to agree, but it means we need to start moving to approve the next
version fairly quickly - which also means moving legacy priv-mode tests.
That's even more work than just updating RV64i tests.
We should do some triage and figure out an order of transitioning the tests.
