### ISSUE TITLE
breakpoint.s undesired behavior when trigger does not exist?

### ISSUE THREAD

**Issue by debs-sifive** [riscv/riscv-compliance#32]
When a trigger doesn't exist, the test goes to the `pass` label. The result is that the signature is not written to after the trigger check, and the target will fail `make verify`. This doesn't seem like the ideal action, since it's valid for a target to have no trigger.

For context, I'm trying to add rocket chip's `Default[RV32]Config` as a target, and it only has one trigger.

**Comment by allenjbaum** [comment]
IF this has been fixed, can we close the issue?
