### ISSUE TITLE
rv32si/ma_fetch.S produces a different signature depending on RVC support

### ISSUE THREAD

**Issue by debs-sifive** [riscv/riscv-compliance#33]
I think this is a similar issue to [fix for ma_fetch](https://github.com/riscv/riscv-compliance/issues/15), but in `rv32si`.

When I run the test with target `spike` with `--isa=rv32ic`, the signature I get is:

```
00000001
ffffffff
00000002
00000003
00000004
00000005
00000006
00000007
ffffffff
  .
  .
  .
```

Which does not match up with the signature produced with `--isa=rv32i`, which matches the [current reference signature](https://github.com/riscv/riscv-compliance/blob/master/riscv-test-suite/rv32si/references/ma_fetch.reference_output).

**Comment by allenjbaum** [comment]
IF this is fixed, can we close it?
