### ISSUE TITLE
rv32imc C.SWSP test5 writes a word outside the binary

### ISSUE THREAD

**Issue by astimonov** [riscv/riscv-compliance#37]
Related issue: #5 
https://github.com/riscv/riscv-compliance/blob/d8e99ee55d5fa3460c0a2f0898dd917a616763fb/riscv-test-suite/rv32imc/src/C-SWSP.S#L86

The test performs a write to offset 252, which is outside of section test_data (32 words).

**Comment by allenjbaum** [comment]
This does need to be fixed; if we are only testing signatures within the test_data section, then this test is effectively bypassed, since its signature isn't checked

**Comment by eroom1966** [comment]
This is a good catch, and more importantly indicates the necessity of the mutation fault testing to be completed for all suites - up until now we only checked this for the RV32I tests

**Comment by allenjbaum** [comment]
If we start to use the SIGUPD macro, I don't think this can happen in
general, though this test deliberately stored values in non-contiguous
locations (don't quite understand why). This test could to use a SIGBASE
macro to set the base to a specific value, which would catch this error
In general, SIGUPD and SIGBASE should do bounds checking and give an
assembler error if basereg+offset is outside the bounds of DATA_START and
DATA_END, and that would catch this type of error.
I am proposing a BASEUPD macro that would update the base register with the
hidden offset value maintained by the SIGUPD macro (this is needed for
tests that use SIGUPD inside loops),
Here, though,  I can see that an OFFSETUPD macro that manually sets the
hidden offset instead would work better.
All of these macros should check that base+offset is within bounds.
