### ISSUE TITLE
RV32I Immediate Operands error

### ISSUE THREAD

**Issue by rongcuid** [riscv/riscv-compliance#67]
I am making a new target of my RISC-V platform, and I encounter these compiler error in the test suite:

```
src/I-RF_x0-01.S:57: Error: illegal operands `xori x0,x0,0xFFFFF803'
src/I-JALR-01.S:291: Error: illegal operands `jalr x0,x3,0xFFFFFFFF'
```
And so on. I used Zephyr SDK 0.10.1, which provides GCC 8.3.0.

I believe that GCC is unhappy with the "sign extension" done by hand, as I could remove these errors by using corresponding negative numbers.

**Comment by eroom1966** [comment]
OK, I have changed these tests, good news still works with my version compiler - I will issue a pull request

**Comment by rongcuid** [comment]
Also, RV32I tests seems to fail on RV64I architectures due to OP and OP-32, OP-IMM and OP-IMM32 difference. Is that intentional?

**Comment by allenjbaum** [comment]
Definitely not intentional. Could you be more specific on the errors you
are seeing so we can track them down?

**Comment by rongcuid** [comment]
I might be wrong. Previously I tried to manually change all the invalid operands to negative numbers. I failed a few of them, and some are my fault. However, I think there are some problems in the tests too.

I failed: ENDIANESS, RF_SIZE, RF_WIDTH, MISALIGNED_JUMP, JAL-01, JALR-01, LUI-01, AUIPC, all loads, SB, SH, and some more.

Of these, LUI-01 is almost definitely not my fault:

```
# Test Begin

# Test part A - general test of LUI

= Assertion Violation =
== File ==
src/I-LUI-01.S
== Line ==
72
== Register ==
x5
== Got ==
0xfffffffffffff000
== Expected ==
0xFFFFF000
```
So is AUIPC:

```
# Test Begin

# Test part A - general test of AUIPC

= Assertion Violation =
== File ==
src/I-AUIPC-01.S
== Line ==
90
== Register ==
x6
== Got ==
0x0000000080000000
== Expected ==
0x00000000
```

LW:

```
# Test Begin

# Test part A1 - test base address + 0

# Test part A1  - Complete

# Test part A2 - test base address - 1

= Assertion Violation =
== File ==
src/I-LW-01.S
== Line ==
80
== Register ==
x25
== Got ==
0xfffffffff33344f4
== Expected ==
0xF33344F4
```
And more.

I notice that all the targets shipped pass a parameter to run the 32-bit variant when running the RV32I tests, and in my understanding, RV64I and RV32I are not really binary compatible (due to OP-32 and OP-IMM32). This leaves my 64-bit only implementation without the majority of tests.

Perhaps this should be a separate issue?

**Comment by allenjbaum** [comment]
I'm guessing the assertions are set up for 32b operands and not 64b.
It is odd that this hasn't been reported previously. The signatures
probably match, which is the most important part, so this may be just a
false negative.
This will likely be fixed in future test suites as there will be completely
different tests for RV64 and RV32, and therefore different assertions (at
worst).

**Comment by rongcuid** [comment]
I do not think the signatures match, especially for the few failures I listed above, RV64I probably needs its own set of tests that covers all instructions, separate from RV32I.

**Comment by neelgala** [comment]
@rongcuid yes the rv64i tests do require their own set and are not complete. Only the rv32i, rv32im, rv32imc, rv32ifencei and rv32icsr are the ones that are currently supported. The 64 bit tests are under development.

**Comment by MarcKarasek** [comment]
I do not see where the original problem with the xori 

src/I-RF_x0-01.S:57: Error: illegal operands `xori x0,x0,0xFFFFF803'
src/I-JALR-01.S:291: Error: illegal operands `jalr x0,x3,0xFFFFFFFF'

has been fixed?  I am seeing the same problem using a 64bit compiler. 

Also: What is the current state of the RV64 tests?

**Comment by allenjbaum** [comment]
I dimly recall having seen this before, and that this is a toolchain issue.
If instead 0xFFFFF803 was encoded as -0x7FD, it would probably work.
Which toolchain are you using?

**Comment by allenjbaum** [comment]
RV64 tests are coming, and we hope to have them merged by the end of next
month.
