### ISSUE TITLE
RV32I/I-IO.S bad file name

### ISSUE THREAD

**Issue by AnttiLukats** [riscv/riscv-compliance#8]
if all other files in the same folder use I-xxx-01.S style then the file I-IO.S should also be named I-IO-01.S

**Comment by Imperas** [comment]
yes this is a wider question that needs to be discussed in the compliance group.
I notice in the compressed instructions, they do not contain an index, this is also the case wit hte imported tests from @aswaterman suite under riscv-tests

**Comment by eroom1966** [comment]
@AnttiLukats 
Could you please issue a pull request to fix the issues reported ?
