### ISSUE TITLE
Undefining `RVTEST_IO_QUIET` for OVPsim uncovers SRL test bugs

### ISSUE THREAD

**Issue by yupferris** [riscv/riscv-compliance#81]
Commenting out [this line](https://github.com/riscv/riscv-compliance/blob/master/riscv-target/riscvOVPsim/compliance_io.h#L33) to enable more verbose test output, the `I-SRL-01` test in the `rv32i` suite fails an assertion:

```
Test Begin
# Test number 1
Assertion violation: file src/I-SRL-01.S, line 49: x3(0000007f) != 0xf0000000
```

Looking at the code for this test case:

```
TEST_RR_OP(srl, x3, x28, x13, 0xf0000000, 0x7ff, 0x4, x5, 12, x6)   # Testcase 3
```

This expands to:

```
li x28, 0x7ff
li x13, 0x4
srl x3, x28, x13
sw x3, 12(x5)
RVTEST_IO_ASSERT_GPR_EQ(x6, x3, 0xf0000000)
```

This should shift the value 0x7ff right by 0x4 bits, which should yield the value 0x7f, which is what we see `x3` contains in the assertion.

I discovered this while testing my own implementation, only to find out that OVPsim uncovers the same error under the same conditions. I think the expected value should be `0x7f`.

When commenting out lines in the test that fail, we see similar errors later:

```
Assertion violation: file src/I-SRL-01.S, line 60: x5(00000000) != 0x1000
Assertion violation: file src/I-SRL-01.S, line 61: x6(00000765) != 0x43210000
Assertion violation: file src/I-SRL-01.S, line 62: x7(00000000) != 0xfffffffe
Assertion violation: file src/I-SRL-01.S, line 74: x10(00000000) != 0x2468
Assertion violation: file src/I-SRL-01.S, line 75: x11(08000000) != 0x0
Assertion violation: file src/I-SRL-01.S, line 76: x12(00ffffed) != 0xcc000000
Assertion violation: file src/I-SRL-01.S, line 77: x13(00000001) != 0xfffffffe
Assertion violation: file src/I-SRL-01.S, line 78: x14(0000ffff) != 0xf8010000
Assertion violation: file src/I-SRL-01.S, line 92: x19(0000007f) != 0xf0000000
Assertion violation: file src/I-SRL-01.S, line 103: x21(00000000) != 0x1000
Assertion violation: file src/I-SRL-01.S, line 104: x22(00000765) != 0x43210000
Assertion violation: file src/I-SRL-01.S, line 105: x23(00000000) != 0xfffffffe
Assertion violation: file src/I-SRL-01.S, line 117: x26(00000000) != 0x2468
Assertion violation: file src/I-SRL-01.S, line 118: x27(08000000) != 0x0
Assertion violation: file src/I-SRL-01.S, line 119: x28(00ffffed) != 0xcc000000
Assertion violation: file src/I-SRL-01.S, line 120: x29(00000001) != 0xfffffffe
Assertion violation: file src/I-SRL-01.S, line 130: x30(0000ffff) != 0xf8010000
```

It seems the simulator is producing correct output in these cases, but the expected values in the test are wrong. This only triggers failures _without_ the [quiet macro defined](https://github.com/riscv/riscv-compliance/blob/master/riscv-target/riscvOVPsim/compliance_io.h#L33), as otherwise, the register values are written to the result area, but not asserted to contain the expected values shown here.

**Comment by eroom1966** [comment]
This is fixed in PR #85 
@simon5656 
@yupferris
