### ISSUE TITLE
doc directory does not build

### ISSUE THREAD

**Issue by dsw** [riscv/riscv-compliance#95]
In the doc/ directory when I type "make" I get this:

> Version number of title and document history do not match

This happens in both release version 0.1 and in the current master HEAD at commit 13e1b57b52f1c0708bc6442a9668c5c01b4eb79e

**Comment by jeremybennett** [comment]
@dsw Thanks for reporting. A limitation of using Asciidoc is that we have to put the version number in two places (in the title and in the document history). The make script checks these match.

Would you like to submit a pull request to fix this?

**Comment by dsw** [comment]
The fix is not obvious to me.

**Comment by neelgala** [comment]
This has been fixed. Closing it for now.
