### ISSUE TITLE
how do I run all of the 64-bit tests, such as those in riscv-test-suite/rv32ui/rv64ui, through, say, spike ?

### ISSUE THREAD

**Issue by dsw** [riscv/riscv-compliance#96]
I find that when I run the spike tests, not all of the 64-bit tests run.  All that seems to run are the 64-bit tests having a "W" in the instruction name, that is, those that are not the namesake of a 32-bit test, such as those in riscv-test-suite/rv64i/src.  In contrast, most of the 64-bit instructions that are the namesake of a 32-bit instruction do not seem to be tested.

I find the following directory that seems to contain 64-bit tests: riscv-test-suite/rv32ui/rv64ui .  This does not seem to participate in the testing of spike.  How come?  I cannot find how to run these tests.  How do I run all of the 64-bit tests through, say, spike?

Am I missing something obvious here?  I could just find a way to hack this in, but it seems that there must be an official way to do this and I would rather use that if there is one.

Perhaps this is related to https://github.com/riscv/riscv-compliance/issues/30 , which seems to suggest that the 64-bit tests are not even finished?

**Comment by allenjbaum** [comment]
https://github.com/riscv/riscv-compliance/tree/master/riscv-test-suite/readme.md lists the standard test suites that are supported. The rv64 tests were quickly ported from some older tests, but are not supported. Most of these have been duplicated in the rv64i tests, so they should be redundant.

You could add them anyway by 
    adding a directory /riscv-target/spike/device/rv64ui and copying the /rv64i/Makefile.include into it , 
   copying a directory riscv-compliance/riscv-test-suite/rv64i  into /rv64ui, 
   modifying the /rv64ui/makefrag file  to include all the tests you want to run, 
   creating reference results in the /references subdirectory
and even then, it isn't clear that this will work.

**Comment by pdonahue-ventana** [comment]
That link is wrong due to case-sensitivity.  Correct link:
https://github.com/riscv/riscv-compliance/blob/master/riscv-test-suite/README.md

**Comment by allenjbaum** [comment]
I knew I should have checked that. Sloppy. Thanks.

**Comment by neelgala** [comment]
the rv64i test suite is not complete and still a WIP. Suggest you look at riscv-tests by andrew for a good starting point for 64-bit tests.
