### ISSUE TITLE
in release 0.1, file riscv-test-suite/rv64i/Makefrag, variable rv64i_sc_tests contains SRAIW twice

### ISSUE THREAD

**Issue by dsw** [riscv/riscv-compliance#97]
in release 0.1, file riscv-test-suite/rv64i/Makefrag, variable rv64i_sc_tests contains "SRAIW" twice; this is still the case in commit 13e1b57b52f1c0708bc6442a9668c5c01b4eb79e

> Makefile:49: target 'SRAIW.elf' given more than once in the same rule

**Comment by dsw** [comment]
I think I fixed this and another similar bug in this pull request:
https://github.com/riscv/riscv-compliance/pull/98

however, see the note in that pull request that this change is tested in release 0.1 but not in HEAD as running the same tests in HEAD that I do in release 0.1 is not working

**Comment by allenjbaum** [comment]
Thanks very much for making the pull request; every little bit helps.

**Comment by neelgala** [comment]
merged and fixed. I have tested riscvOVPsim and spike and they seem to pass.
